spring.application.name=notification_service
server.port=8081
spring.kafka.bootstrap-servers=${LOCALHOST}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.host=smtp.yandex.ru
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.yandex.ru
mail.recipient.test=${MAIL_RECIPIENT_TEST}